supports the issues/331 mentioned in points 2, 3, 4
wechat-miniprogram/api-typings pull request #332
Opened 2024-09-02 07:37 UTC by lv-z-l

1. Component Object、Array 的 property支持通过 as 明确指定property的类型
2. 支持Component 传自定义属性
3. Component 当组件无 properties 选项时，xxx未在 data 中声明，this.data.xxx 不报 TS2339 error 的问题

2024-09-02 09:10 UTC, Mister-Hope commented
lgtm

2024-09-02 09:10 UTC, Mister-Hope approved these changes

2024-09-03 03:50 UTC, lv-z-l commented
@LastLeaf 辛苦帮忙review

2024-09-03 05:44 UTC, SgLy requested changes

2024-09-03 05:44 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +        Partial<TCustomInstanceProperty> &
框架目前并没有这样的特性，类型定义应当准确表达实际实现，而不是「应该支持」

2024-09-03 05:44 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +            // 给泛型默认值，避免出现当组件无 properties 选项时
注释中不应该解释为何这样书写定义，而应该注明需要类型使用者了解或注意的内容（例如相关文档）；如果没有需要使用者留意的内容可以直接删掉注释

2024-09-03 05:44 UTC, SgLy commented on test/component.test.ts
> +      observer(newVal: number, oldVal: number) {
这里为什么新增了类型声明？修改后的定义无法支持这里的自动推导吗？

2024-09-03 06:21 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +        Partial<TCustomInstanceProperty> &
这个case在业务上非常常见，比如想在this上暂存类似定时器的临时变量，比如：
![image](https://github.com/user-attachments/assets/b8f9f6f1-527a-43f2-a47b-a21657831d6d)
会受限于TS类型编译，而采用繁琐的写法。
![image](https://github.com/user-attachments/assets/5afe0500-13b9-4700-bc43-3db942d07cb1)
出于这个考量，作出修改，如果觉得不合适，我将去掉。

2024-09-03 07:51 UTC, lv-z-l commented on test/component.test.ts
> +      observer(newVal: number, oldVal: number) {
> 这里为什么新增了类型声明？修改后的定义无法支持这里的自动推导吗？

这里确实是修改引起了无法支持这里的自动推导，已经重新实现了

2024-09-03 07:52 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +            // 给泛型默认值，避免出现当组件无 properties 选项时
> 注释中不应该解释为何这样书写定义，而应该注明需要类型使用者了解或注意的内容（例如相关文档）；如果没有需要使用者留意的内容可以直接删掉注释

已删除注释

2024-09-03 09:31 UTC, SgLy requested changes

2024-09-03 09:31 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +    // 支持 Array、Object 的 property 通过 value as ValueType 的方式明确 property 的类型
这个也删一下吧，其他的没问题了

2024-09-03 11:01 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +    // 支持 Array、Object 的 property 通过 value as ValueType 的方式明确 property 的类型
done

2024-09-03 11:13 UTC, SgLy approved these changes

2024-09-03 11:13 UTC, merged

2024-09-04 10:09 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +        Partial<TCustomInstanceProperty> &
@SgLy 关于这个点，我还是想不通，看下面的例子：
![image](https://github.com/user-attachments/assets/68039b38-3958-4612-aef4-c5f4619becca)
目前的设计，是支持this上自定义属性的，所以我觉得这么改没问题的啊，辛苦再确认下呢！

2024-10-04 08:00 UTC, yangmingshan commented
> Component Object、Array 的 property支持通过 as 明确指定property的类型

我觉得没必要限制于 Object 跟 Array，Number 跟 String 甚至 Boolean 也可以通过 `as` 指定更加准确的类型。

```ts
Component({
  properties: {
    num: {
      type: Number,
      value: 0 as 0 | 1
    },
    str: {
      type: String,
      value: 'foo' as 'foo' | 'bar'
    }
  }
})
```

可以修改为：

```diff
- type ArrayOrObject = ArrayConstructor | ObjectConstructor
- type FullPropertyToData<T extends AllFullProperty> = T['type'] extends ArrayOrObject ? unknown extends T['value'] ? ValueType<T['type']> : T['value'] : ValueType<T['type']>
+ type FullPropertyToData<T extends AllFullProperty> = T['type'] extends null ? any : unknown extends T['value'] ? ValueType<T['type']> : T['value']
```

@lv-z-l @Mister-Hope @SgLy 你们觉得呢？