feat: behavior ts type support
wechat-miniprogram/api-typings pull request #333
Opened 2024-09-03 11:55 UTC by lv-z-l

behavior ts type support

2024-09-04 06:29 UTC, lv-z-l commented
@SgLy @Mister-Hope 两位老哥，来review下这个pr

2024-09-04 06:36 UTC, SgLy commented
这种实现方式之前在 #230 中讨论过，它改变了 `Behavior()` 的返回值类型，变得和实际的类型不一样了，这点是比较难接受的。例如测试用例中的这种构造，会变成可以通过 TS 编译但不可能正确运行的：
```typescript
// wrong use case
Component({
  behaviors: [{data: {}, properties: {}, methods: {}}],
})
```

这里是否有可能用更接近 `string` 的类型来携带 `Behavior` 需要的推导信息？我之前有过类似这样的思路，不过还没有深入尝试：
```typescript
declare const virtualBehaviorKeySymbol: unique symbol
type BehaviorIdentifier<T> = string & { [virtualBehaviorKeySymbol]: SomeBehaviorInstanceContext<T> }
```

2024-09-04 07:17 UTC, lv-z-l commented
确实，为了类型推导改变了实际的类型比较难接受，我再思考下，还有没有其他方案

2024-09-04 08:03 UTC, lv-z-l commented
> 这种实现方式之前在 #230 中讨论过，它改变了 `Behavior()` 的返回值类型，变得和实际的类型不一样了，这点是比较难接受的。例如测试用例中的这种构造，会变成可以通过 TS 编译但不可能正确运行的：
> 
> ```ts
> // wrong use case
> Component({
>   behaviors: [{data: {}, properties: {}, methods: {}}],
> })
> ```
> 
> 这里是否有可能用更接近 `string` 的类型来携带 `Behavior` 需要的推导信息？我之前有过类似这样的思路，不过还没有深入尝试：
> 
> ```ts
> declare const virtualBehaviorKeySymbol: unique symbol
> type BehaviorIdentifier<T> = string & { [virtualBehaviorKeySymbol]: SomeBehaviorInstanceContext<T> }
> ```

用更接近 `string` 的类型来携带 `Behavior` 需要的推导信息，我感觉除了交叉类型，应该没有更好的方案了，也问了下GPT-4o。
![image](https://github.com/user-attachments/assets/6668ada4-81fb-4d76-bba0-cede809f5477)
老哥怎么看

2024-09-04 08:16 UTC, lv-z-l commented
我觉得交叉类型是可接受的实现方式，表明了返回类型是 string 的同时，也能够支持类型推导，除了在写 test 用例时不能直接写：
![image](https://github.com/user-attachments/assets/c7bd3b1e-a4de-4140-ad65-24ff7f5d6e72)
不过话又说回来，这种写法已经违背了behavior 的初衷（抽象可复用的部分），正常通过Behavior({})的方式使用才是正确的姿势。

2024-09-05 02:01 UTC, lv-z-l commented
@SgLy 重新实现了，review下
![image](https://github.com/user-attachments/assets/d9619062-1957-41a5-be34-2dbe9243c5dd)

2024-09-06 07:35 UTC, SgLy commented
`Behavior` 是能使用 `Behavior` 的，看看能不能实现类似下面这种情况的推导？可以补个用例
```typescript
const behaviorA = Behavior({
  data: {
    A: 1,
  }
})

const behaviorB = Behavior({
  behaviors: [behaviorA],
  data: {
    B: 2
  }
})

Component({
  behaviors: [behaviorB],
  methods: {
    fn() {
      console.log(this.data.A) // expected 1
      console.log(this.data.B) // expected 2
    }
  }
})
```

2024-09-06 08:26 UTC, lv-z-l commented
> `Behavior` 是能使用 `Behavior` 的，看看能不能实现类似下面这种情况的推导？可以补个用例
> 
> ```ts
> const behaviorA = Behavior({
>   data: {
>     A: 1,
>   }
> })
> 
> const behaviorB = Behavior({
>   behaviors: [behaviorA],
>   data: {
>     B: 2
>   }
> })
> 
> Component({
>   behaviors: [behaviorB],
>   methods: {
>     fn() {
>       console.log(this.data.A) // expected 1
>       console.log(this.data.B) // expected 2
>     }
>   }
> })
> ```

应该没啥问题，我抽空搞一下

2024-09-09 02:51 UTC, lv-z-l commented
> `Behavior` 是能使用 `Behavior` 的，看看能不能实现类似下面这种情况的推导？可以补个用例
> 
> ```ts
> const behaviorA = Behavior({
>   data: {
>     A: 1,
>   }
> })
> 
> const behaviorB = Behavior({
>   behaviors: [behaviorA],
>   data: {
>     B: 2
>   }
> })
> 
> Component({
>   behaviors: [behaviorB],
>   methods: {
>     fn() {
>       console.log(this.data.A) // expected 1
>       console.log(this.data.B) // expected 2
>     }
>   }
> })
> ```

2024-09-09 02:53 UTC, lv-z-l commented
@SgLy 支持了Behavior 中使用 Behavior 的类型推导，抽空来看下。https://github.com/wechat-miniprogram/api-typings/pull/333/commits/57d4c82e8252ca2105fffe177c8fe1d42bc6fb75

2024-09-11 11:24 UTC, SgLy requested changes

2024-09-11 11:24 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +            TBehavior extends BehaviorOption = [],
这个默认值是有必要的不，能不能和上面三个保持一致（都有默认值或者都没有）

2024-09-11 11:24 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +            TBehavior extends BehaviorOption = [],
（上面的 `Options` 也是）

2024-09-11 11:24 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> +    type IAnyArray = []
这个或许应该是 `IEmptyArray` 好一点？（和 `any[]` 区别）

可以挪到 `index.d.ts` 里面和 `IAnyObject` 一起

2024-09-11 11:24 UTC, SgLy commented on types/wx/lib.wx.component.d.ts
> -            /** 组件数据，**包括内部数据和属性值** */
这个注释被改没了，可以补回来一下

2024-09-11 11:24 UTC, SgLy commented on types/wx/lib.wx.behavior.d.ts
> +        ): BehaviorIdentifier & RealBehaviorType<TData, TProperty, TMethod, TBehavior>
这个 `RealBehaviorType` 可能还是直接交叉进 `BehaviorIdentifier` 好一点，比较方便外面引用，比如

```typescript
const behaviorA: BehaviorIdentifier = Behavior()
```

或者

```typescript
const myBehaviors: Record<string, BehaviorIdentifier> = {}
Component({
  behaviors: [myBehaviors.computed],
})
```

2024-09-12 02:40 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> -            /** 组件数据，**包括内部数据和属性值** */
done

2024-09-12 02:42 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +            TBehavior extends BehaviorOption = [],
done

2024-09-12 02:42 UTC, lv-z-l commented on types/wx/lib.wx.component.d.ts
> +    type IAnyArray = []
done

2024-09-12 02:42 UTC, lv-z-l commented on types/wx/lib.wx.behavior.d.ts
> +        ): BehaviorIdentifier & RealBehaviorType<TData, TProperty, TMethod, TBehavior>
done

2024-09-13 03:05 UTC, lv-z-l commented
@SgLy 老哥，确认下评论，没问题 merge 下，我们还等着用呢。

2024-09-13 08:45 UTC, SgLy approved these changes

2024-09-13 08:46 UTC, merged

2024-09-13 08:47 UTC, SgLy commented
这两个 PR 改了一些之前的公开接口，有些 breaking change，应该是要发一个 major 了

2024-09-13 09:58 UTC, lv-z-l commented
> 这两个 PR 改了一些之前的公开接口，有些 breaking change，应该是要发一个 major 了

嗯嗯